### ISSUE TITLE
멘토 공지사항

### ISSUE THREAD

**Issue by Manicarus** [Manicarus/BJCloud#8]
# 2016년 1학기 멘토링 결산
1. 멘토링 출석 및 과제 점수
   미흡한 인원 이메일로 보고
   swkang7229@gmail.com
2. 차기 회장, 부회장 자기소개서 받기
   [자기소개서 양식](https://github.com/Manicarus/BJCloud/blob/master/Administration/INTERVIEW_Consul_2016.md)
   배지훈 회장이 7월 22일 이후 보고하기
3. 멘토링 진행률 보고 (열혈강의 교재 기준)
   ex. Shift (p.250까지)
   **아래 댓글로 보고**

**Comment by jihoonn** [comment]
배지훈
현재(7월 7일기준)
전역변수 전까지 완료

**Comment by jihoonn** [comment]
형 근데 자소서 양식에 3번이 추가되어있네요?
작년일때문에 그런가?
저희 간부회의 한번 해야할거같아요

**Comment by Ikalli** [comment]
함수까지 완료했습니다
교재 기준 p.221쪽 까지 했어요

**Comment by alphalife3314** [comment]
Shift (p.221까지)
함수까지 완료
